name: Scheduled ETL Pipeline

on:
  # Permite que você rode este workflow manualmente pela aba "Actions" do GitHub
  workflow_dispatch:

  # Agenda a execução para todos os dias às 3 da manhã (UTC)
  schedule:
    - cron: '0 3 * * *'

jobs:
  run-etl-pipeline:
    runs-on: ubuntu-latest  # Usa uma máquina virtual Linux fornecida pelo GitHub

    steps:
      - name: 1. Checkout do Repositório
        uses: actions/checkout@v4

      - name: 2. Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.8' 

      - name: 3. Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Executar o Pipeline de ETL
        # Este passo usa os segredos que configuramos no GitHub
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python scripts/etl/01_extract.py
          python scripts/etl/02_transform.py
          python scripts/etl/03_load.py